services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn banas.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --access-logfile - --error-logfile - --capture-output --log-level info --enable-stdio-inheritance"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      # Add these New Relic variables here
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LOG=stdout
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ./media:/app/media
      - static_volume:/app/static
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume: