version: '3.8'

services:
  api:
    build: .
    command: >
      sh -c "python manage.py migrate &&
           gunicorn banas.wsgi:application --bind 0.0.0.0:8000 --workers 2 
           --access-logfile - 
           --error-logfile - 
           --capture-output 
           --log-level debug 
           --enable-stdio-inheritance"
    env_file:
      - .env  # Only loads local Django + DB vars
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - static_volume:/app/static
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: