# Generated by Django 4.0.2 on 2023-06-10 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('addedby', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_route', to='route.route')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('due', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('addedby', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
