# Generated by Django 4.0.2 on 2023-10-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='customer.customer'),
        ),
    ]
