# Generated by Django 4.0.2 on 2023-10-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customeraccount_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='customer.customer'),
        ),
    ]
