# Generated by Django 4.2 on 2024-02-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_email'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customer',
            index_together={('id',)},
        ),
        migrations.AlterIndexTogether(
            name='customeraccount',
            index_together={('id', 'customer_name')},
        ),
    ]
