# Generated by Django 4.2 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='total_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
