# Generated by Django 4.2 on 2024-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customeraccount_total_paid'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customeraccount',
            index_together={('id', 'customer_name', 'due')},
        ),
    ]
