# Generated by Django 4.2 on 2024-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customeraccount_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sequence_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
