# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_sequence_no'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customer_cu_id_5426ca_idx',
            old_fields=('id',),
        ),
        migrations.RenameIndex(
            model_name='customeraccount',
            new_name='customer_cu_id_1ac322_idx',
            old_fields=('id', 'customer_name', 'due'),
        ),
    ]
