# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_sequence_no'),
    ]

    operations = []
