# Generated by Django 6.0.2 on 2026-02-22 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_customer_id_customer_cu_id_5426ca_idx_and_more'),
        ('route', '0003_rename_route_id_route_route_id_b9f012_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['route', 'active'], name='customer_cu_route_i_a8428a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='customer_cu_first_n_a7fb89_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-date_added'], name='customer_cu_date_ad_1f1d66_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['customer_name', 'due'], name='customer_cu_custome_fe27be_idx'),
        ),
    ]
