# Generated by Django 6.0.2 on 2026-02-25 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customer_customer_cu_id_5426ca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[6789]\\d{9}$')]),
        ),
    ]
