# Generated by Django 4.0.2 on 2023-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='rounf_off_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
