# Generated by Django 4.0.2 on 2023-10-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customeraccount_customer_name'),
        ('payment', '0002_customerpayment_rounf_off_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payment', to='customer.customer'),
        ),
    ]
