# Generated by Django 4.2 on 2024-02-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_index_together_and_more'),
        ('payment', '0003_alter_customerpayment_customer_name'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customerpayment',
            index_together={('id', 'customer_name')},
        ),
    ]
