# Generated by Django 4.2 on 2024-04-26 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customeraccount_index_together'),
        ('payment', '0004_alter_customerpayment_index_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_payment',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pending_amount', models.IntegerField(blank=True, null=True)),
                ('paid_amount', models.IntegerField()),
                ('rounf_off_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('addedby', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments_partitioned', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
