# Generated by Django 4.2.23 on 2025-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_delete_customer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
