# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_customerpayment_notes_customerpayment_payment_method'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerpayment',
            new_name='payment_cus_id_fdb0f5_idx',
            old_fields=('id', 'customer_name'),
        ),
    ]
