# Generated by Django 6.0.2 on 2026-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customer_customer_cu_id_5426ca_idx_and_more'),
        ('payment', '0008_rename_customerpayment_id_customer_name_payment_cus_id_fdb0f5_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerpayment',
            name='payment_cus_id_fdb0f5_idx',
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer_name', '-date'], name='payment_cus_custome_6f598c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['date'], name='payment_cus_date_37cbe7_idx'),
        ),
    ]
