# Generated by Django 6.0.2 on 2026-02-28 12:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_customerpayment_payment_cus_id_fdb0f5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
