# Generated by Django 4.2 on 2023-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyentry', '0006_pending_daily_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
