# Generated by Django 4.2 on 2024-02-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_index_together_and_more'),
        ('dailyentry', '0008_dailyentry_dashboard'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customer_daily_entry_monthly',
            index_together={('customer',)},
        ),
        migrations.AlterIndexTogether(
            name='customer_qr_code',
            index_together={('customer',)},
        ),
        migrations.AlterIndexTogether(
            name='dailyentry',
            index_together={('id', 'customer')},
        ),
        migrations.AlterIndexTogether(
            name='pending_daily_entry',
            index_together={('id', 'customer')},
        ),
    ]
