# Generated by Django 4.2 on 2024-04-26 19:06

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customeraccount_index_together'),
        ('dailyentry', '0009_alter_customer_daily_entry_monthly_index_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_daily_entry_partition',
            fields=[
                ('date_added', models.DateTimeField(default=datetime.datetime)),
                ('cooler', models.IntegerField()),
                ('addedby', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_daily_entry_partition_test', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
