# Generated by Django 4.2 on 2024-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyentry', '0012_alter_customer_daily_entry_partition_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_daily_entry_partition',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
