# Generated by Django 4.2 on 2024-05-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyentry', '0014_alter_customer_daily_entry_partition_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_daily_entry_partition',
        ),
    ]
