# Generated by Django 4.2 on 2024-06-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_sequence_no'),
        ('dailyentry', '0015_delete_customer_daily_entry_partition'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='dailyentry',
            index_together={('date_added',), ('id', 'customer'), ('customer', 'date_added')},
        ),
    ]
