# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyentry', '0016_alter_dailyentry_index_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer_daily_entry_monthly',
            new_name='dailyentry__custome_d2c7f1_idx',
            old_fields=('customer',),
        ),
        migrations.RenameIndex(
            model_name='customer_qr_code',
            new_name='dailyentry__custome_a25846_idx',
            old_fields=('customer',),
        ),
        migrations.RenameIndex(
            model_name='dailyentry',
            new_name='dailyentry__id_6ed5fe_idx',
            old_fields=('id', 'customer'),
        ),
        migrations.RenameIndex(
            model_name='dailyentry',
            new_name='dailyentry__custome_5213e0_idx',
            old_fields=('customer', 'date_added'),
        ),
        migrations.RenameIndex(
            model_name='dailyentry',
            new_name='dailyentry__date_ad_e18733_idx',
            old_fields=('date_added',),
        ),
        migrations.RenameIndex(
            model_name='pending_daily_entry',
            new_name='dailyentry__id_f30238_idx',
            old_fields=('id', 'customer'),
        ),
    ]
