# Generated by Django 6.0.2 on 2026-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customer_customer_cu_id_5426ca_idx_and_more'),
        ('dailyentry', '0017_rename_customer_daily_entry_monthly_customer_dailyentry__custome_d2c7f1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyentry',
            name='dailyentry__id_6ed5fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyentry',
            name='dailyentry__custome_5213e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='pending_daily_entry',
            name='dailyentry__id_f30238_idx',
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['customer', '-date_added'], name='dailyentry__custome_fd858e_idx'),
        ),
        migrations.AddIndex(
            model_name='pending_daily_entry',
            index=models.Index(fields=['customer', '-date_added'], name='dailyentry__custome_e2374b_idx'),
        ),
        migrations.AddIndex(
            model_name='pending_daily_entry',
            index=models.Index(fields=['date_added'], name='dailyentry__date_ad_6b370a_idx'),
        ),
    ]
