# Generated by Django 6.0.2 on 2026-02-28 12:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyentry', '0018_remove_dailyentry_dailyentry__id_6ed5fe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pending_daily_entry',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
