# Generated by Django 4.0.2 on 2023-02-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyentry',
            old_name='date',
            new_name='date_added',
        ),
    ]
