# Generated by Django 4.0.2 on 2022-02-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='route',
            field=models.CharField(default='jeep', max_length=100),
            preserve_default=False,
        ),
    ]
