# Generated by Django 4.0.2 on 2022-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expanded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
