# Generated by Django 4.0.2 on 2023-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_date_dailyentry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='pending_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
