# Generated by Django 4.0.2 on 2022-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_customer_date_remove_customer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
