# Generated by Django 4.0.2 on 2023-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_customerpayment_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='expanded',
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
