# Generated by Django 4.0.2 on 2022-02-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_dailyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.route'),
        ),
    ]
