# Generated by Django 4.0.2 on 2023-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_customer_expanded_customer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
