# Generated by Django 4.0.2 on 2022-09-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_customer_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerbill',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerbill',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='addedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updatedby',
            field=models.CharField(default='Aman', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_name',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.customer'),
        ),
    ]
