# Generated by Django 4.0.2 on 2022-02-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
