# Generated by Django 4.0.2 on 2022-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_customer_addedby_customer_updatedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerbill',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='addedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='updatedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
