# Generated by Django 4.0.2 on 2023-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_dailyentry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
