# Generated by Django 4.0.2 on 2022-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_customer_addedby_alter_customeraccount_addedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='pending_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
