# Generated by Django 4.0.2 on 2022-02-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_customer_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.customer'),
        ),
    ]
