# Generated by Django 4.0.2 on 2023-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_dailyentry_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
        migrations.DeleteModel(
            name='CustomerBill',
        ),
        migrations.DeleteModel(
            name='CustomerPayment',
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
