# Generated by Django 4.0.2 on 2022-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_dailyentry_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
