# Generated by Django 4.0.2 on 2022-02-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_customerpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='current_due',
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.IntegerField()),
                ('customer_name', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.customer')),
            ],
        ),
    ]
