# Generated by Django 4.0.2 on 2022-02-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_remove_customer_current_due_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
