# Generated by Django 4.0.2 on 2022-02-07 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_customerbill_date_alter_customerbill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-02-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
