# Generated by Django 4.0.2 on 2022-02-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_customeraccount_date_alter_customeraccount_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
    ]
