# Generated by Django 4.0.2 on 2022-02-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_customeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
