# Generated by Django 4.0.2 on 2023-10-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customeraccount_customer_name'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bill', to='customer.customer'),
        ),
    ]
