# Generated by Django 4.2 on 2024-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customeraccount_total_paid'),
        ('bills', '0003_alter_customerbill_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customerbill',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterIndexTogether(
            name='customerbill',
            index_together={('id', 'customer_name', 'bill_number')},
        ),
    ]
