# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_number_generator'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerbill',
            new_name='bills_custo_id_04b535_idx',
            old_fields=('id', 'customer_name', 'bill_number'),
        ),
    ]
