# Generated by Django 6.0.2 on 2026-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_rename_customerbill_id_customer_name_bill_number_bills_custo_id_04b535_idx'),
        ('customer', '0012_rename_customer_id_customer_cu_id_5426ca_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerbill',
            name='bills_custo_id_04b535_idx',
        ),
        migrations.AlterField(
            model_name='customerbill',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customerbill',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='customerbill',
            index=models.Index(fields=['bill_number'], name='bills_custo_bill_nu_0d49c8_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbill',
            index=models.Index(fields=['customer_name', '-from_date'], name='bills_custo_custome_43e664_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbill',
            index=models.Index(fields=['from_date', 'to_date'], name='bills_custo_from_da_5f0e72_idx'),
        ),
    ]
