# Generated by Django 6.0.2 on 2026-02-28 12:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_remove_customerbill_bills_custo_id_04b535_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_number_generator',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbill',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
