# Generated by Django 4.2 on 2024-02-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='route',
            index_together={('id',)},
        ),
    ]
