# Generated by Django 6.0.2 on 2026-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_index_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='route',
            new_name='route_route_id_b9f012_idx',
            old_fields=('id',),
        ),
    ]
