# Generated by Django 6.0.2 on 2026-02-28 12:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_rename_route_id_route_route_id_b9f012_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
